project: 
  type: website
  output-dir: docs
  
website:
  title: "Maths"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Topics"
        menu:
          - number_theory/factors-of-factorials.qmd
          
format:
  html:
    theme: flatly
    mainfont: "Montserrat"
    monofont: "JetBrains Mono"
    page-layout: full
    css: styles.css
    #theme-algo: light
    #linkcolor: "#7894B3"
    #monobackgroundcolor: "#f8f9fa"
    toc: true
    code-fold: true
    number-sections: true
    date-format: "DD MMM YYYY"